DROP TABLE BOARD;
DROP TABLE USER;

CREATE TABLE USER 
(
  USERID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
, NAME VARCHAR(20) NOT NULL 
, EMAIL VARCHAR(45) NOT NULL UNIQUE
, PW VARCHAR(45) NOT NULL 
)ENGINE = InnoDB;

INSERT INTO USER(NAME, EMAIL, PW) VALUE('정은주', 'eun01300714@gmail.com', '1234');
INSERT INTO USER(NAME, EMAIL, PW) VALUE('HELLO1', 'eun@gmail.com', '1234');

CREATE TABLE BOARD 
(
  USERID INT NOT NULL
, BOARDID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
, TITLE VARCHAR(45) NOT NULL
, CONTENT BLOB NOT NULL
, STARTTIME TIMESTAMP NOT NULL
, ENDTIME TIMESTAMP NOT NULL
, FOREIGN KEY(USERID) REFERENCES USER(USERID)
)ENGINE = InnoDB;

INSERT INTO BOARD(USERID, TITLE, CONTENT, STARTTIME, ENDTIME) VALUE(1, 'Chocolate', 'Chocolate Festival', NOW(), NOW());

CREATE TABLE COMMENTS 
(
  BOARDID INT NOT NULL 
, COMMENTID INT NOT NULL 
, WRITERID INT NOT NULL 
, CONTENT VARCHAR(200) NOT NULL 
, DEPTH INT DEFAULT 0 
, PARENTID INT
);